version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "Enhancement"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/wred-client"
    labels:
      - "Enhancement"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/wred-server"
    labels:
      - "Enhancement"
    schedule:
      interval: "daily"
